livros_padrao = [
    ("Dom Casmurro", "Machado de Assis", "Nova Fronteira", "Romance", 5),
    ("Capitães da Areia", "Jorge Amado", "Companhia das Letras", "Drama", 4),
    ("Grande Sertão: Veredas", "João Guimarães Rosa", "Global", "Literatura Brasileira", 3),
    ("O Cortiço", "Aluísio Azevedo", "Ática", "Naturalismo", 5),
    ("Vidas Secas", "Graciliano Ramos", "Record", "Regionalismo", 6),
    ("1984", "George Orwell", "Companhia das Letras", "Distopia", 5),
    ("Admirável Mundo Novo", "Aldous Huxley", "Globo", "Ficção Científica", 4),
    ("A Revolução dos Bichos", "George Orwell", "BestBolso", "Sátira", 6),
    ("O Pequeno Príncipe", "Antoine de Saint-Exupéry", "Agir", "Fábula", 10),
    ("A biblioteca da meia noite", "Matt Haig", "Bertrand Brasil", "Ficção científica", 8),
    ("Senhor dos Anéis: A Sociedade do Anel", "J.R.R. Tolkien", "Martins Fontes", "Fantasia", 4),
    ("Jogos Vorazes", "Suzanne Collins", "Rocco", "Ação", 6),
    ("O Código Da Vinci", "Dan Brown", "Sextante", "Suspense", 5),
    ("O Hobbit", "J.R.R. Tolkien", "Martins Fontes", "Fantasia", 4),
    ("O Nome do Vento", "Patrick Rothfuss", "Arqueiro", "Fantasia", 5),
    ("A Menina que Roubava Livros", "Markus Zusak", "Intrínseca", "Drama", 6),
    ("Coraline", "Neil Gaiman", "Rocco", "Fantasia", 3),
    ("O Apanhador no Campo de Centeio", "J.D. Salinger", "Ed. do Autor", "Romance", 5),
    ("It: A Coisa", "Stephen King", "Suma", "Terror", 4),
    ("Orgulho e Preconceito", "Jane Austen", "Penguin", "Romance", 5),
    ("Os Cem Anos de Lenni e Margot", "Marianne Cronin", "Intrínseca", "Romance", 7),
    ("Maus", "Art Spiegelman", "Companhia das Letras", "História em Quadrinhos", 4),
]
