livros_padrao = [
    #Livros clássicos e populares
    ("Dom Casmurro", "Machado de Assis", "Nova Fronteira", "Romance", 5),
    ("Capitães da Areia", "Jorge Amado", "Companhia das Letras", "Drama", 4),
    ("Grande Sertão: Veredas", "João Guimarães Rosa", "Global", "Literatura Brasileira", 3),
    ("O Cortiço", "Aluísio Azevedo", "Ática", "Naturalismo", 5),
    ("Vidas Secas", "Graciliano Ramos", "Record", "Regionalismo", 6),
    ("1984", "George Orwell", "Companhia das Letras", "Distopia", 5),
    ("Admirável Mundo Novo", "Aldous Huxley", "Globo", "Ficção Científica", 4),
    ("A Revolução dos Bichos", "George Orwell", "BestBolso", "Sátira", 6),
    ("O Pequeno Príncipe", "Antoine de Saint-Exupéry", "Agir", "Fábula", 10),
    ("A biblioteca da meia noite", "Matt Haig", "Bertrand Brasil", "Ficção científica", 8),
    ("Senhor dos Anéis: A Sociedade do Anel", "J.R.R. Tolkien", "Martins Fontes", "Fantasia", 4),
    ("Jogos Vorazes", "Suzanne Collins", "Rocco", "Ação", 6),
    ("O Código Da Vinci", "Dan Brown", "Sextante", "Suspense", 5),
    ("O Hobbit", "J.R.R. Tolkien", "Martins Fontes", "Fantasia", 4),
    ("O Nome do Vento", "Patrick Rothfuss", "Arqueiro", "Fantasia", 5),
    ("A Menina que Roubava Livros", "Markus Zusak", "Intrínseca", "Drama", 6),
    ("Coraline", "Neil Gaiman", "Rocco", "Fantasia", 3),
    ("O Apanhador no Campo de Centeio", "J.D. Salinger", "Ed. do Autor", "Romance", 5),
    ("It: A Coisa", "Stephen King", "Suma", "Terror", 4),
    ("Orgulho e Preconceito", "Jane Austen", "Penguin", "Romance", 5),
    ("Os Cem Anos de Lenni e Margot", "Marianne Cronin", "Intrínseca", "Romance", 7),
    ("Maus", "Art Spiegelman", "Companhia das Letras", "História em Quadrinhos", 4),
    ("Cemitério de Dragões", "Rafael Draccon", "Leya", "Fantasia", 5),
    ("É assim que se perde a guerra do tempo", "Amal El-Mohtar e Max Gladstone", "Mor", "Ficção Científica", 3),
    
    #Revistas e livros técnicos
    ("Revista Superinteressante", "Editora Abril", "Superinteressante", "Ciência e Tecnologia", 10),
    ("Revista Veja", "Editora Abril", "Veja", "Atualidades", 10),
    ("Python Fluente", "Luciano Ramalho", "O'Reilly", "Programação", 5),
    ("Aprenda Computação com Python", "Charles Severance", "Novatec", "Programação", 4),
    ("Estruturas de Dados e Algoritmos com Python", "Michael T. Goodrich", "Bookman", "Programação", 3),
    ("Aprenda a Programar com Python", "Al Sweigart", "Novatec", "Programação", 4),
    ("Aprenda a Programar com JavaScript", "Eloquent JavaScript", "Marijn Haverbeke", "Programação", 4),
    ("Aprenda a Programar com Java", "Cay S. Horstmann", "Bookman", "Programação", 3),
    ("Aprenda a Programar com C#", "C# 7.0 in a Nutshell", "Joseph Albahari", "Programação", 3),
    ("Aprenda a Programar com C++", "C++ Primer", "Stanley B. Lippman", "Programação", 3),
    ("Aprenda a Programar com Ruby", "Programming Ruby", "Dave Thomas", "Programação", 3),
    ("Aprenda a Programar com PHP", "PHP & MySQL: Novice to Ninja", "Tom Butler e Kevin Yank", "Programação Web", 4),
    ("Aprenda a Programar com HTML e CSS", "HTML and CSS: Design and Build Websites", "Jon Duckett", "Web Design", 4),
    ("Aprenda a Programar com SQL", "Learning SQL", "Alan Beaulieu", "Banco de Dados", 4),
    ("Aprenda a Programar com NoSQL", "NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence", "Pramod J. Sadalage e Martin Fowler", "Banco de Dados NoSQL", 3),
    ("Aprenda a Programar com Git e GitHub", "Pro Git", "Scott Chacon e Ben Straub", "Controle de Versão", 4),
    
    #Quadrinhos e Graphic Novels
    ("Watchmen", "Alan Moore e Dave Gibbons", "Panini Comics", "Super-heróis", 5),
    ("Sandman", "Neil Gaiman", "Panini Comics", "Fantasia", 4),
    ("Maus: A História de um Sobrevivente", "Art Spiegelman", "Companhia das Letras", "História em Quadrinhos", 3),
    ("Bone: A Saga Completa", "Jeff Smith", "Devir", "Fantasia", 4),
    ("Saga: Volume 1", "Brian K. Vaughan e Fiona Staples", "Devir", "Ficção Científica", 5),
    ("Scott Pilgrim Contra o Mundo", "Bryan Lee O'Malley", "Quadrinhos na Cia.", "Comédia Romântica", 4),
    ("Akira: Volume 1", "Katsuhiro Otomo", "JBC", "Cyberpunk", 3),
    ("Dragon Ball: Volume 1", "Akira Toriyama", "JBC", "Aventura", 5),
    ("Naruto: Volume 1", "Masashi Kishimoto", "Panini Comics", "Aventura", 5),
    ("One Piece: Volume 1", "Eiichiro Oda", "Panini Comics", "Aventura", 6),
    ("Turma da Mônica: Laços", "Vitor e Lu Cafaggi", "Panini Comics", "Infantil", 4),
    ("Turma da Mônica: Lições", "Vitor e Lu Cafaggi", "Panini Comics", "Infantil", 4),
    ("Asterix: O Gaulês", "René Goscinny e Albert Uderzo", "Editora Record", "Aventura", 5),
    ("Tintim: As Aventuras de Tintim", "Hergé", "Editora Record", "Aventura", 5),
    ("Garfield: Garfield Come Tudo", "Jim Davis", "L&PM Pocket", "Comédia", 6),
    ("Peanuts: O Melhor de Charlie Brown", "Charles M. Schulz", "L&PM Pocket", "Comédia", 5),
    ("Calvin e Haroldo: Um Mundo Diferente", "Bill Watterson", "L&PM Pocket", "Comédia", 4),
]
